### PR TITLE
fix: asyncio login logout in notebook

### PR DESCRIPTION
**Pull request by bwanglzu**
This PR should fix hubble login in notebook:

096B3778-8C38-44BB-B5A0-46B1220F8629

### CODE REVIEW

**Comment by mapleeit** [comment]
But this doesn't solve the root problem, right? User can't open browser, so there is still no way to login in Notebook? 

How do you guys bypass this problem @bwanglzu

**Comment by bwanglzu** [comment]
@mapleeit i didn't get you. I logged in from browser in the notebook.

**Comment by mapleeit** [comment]
I mean user need to open a browser when they run `.login()` 

https://github.com/jina-ai/hubble-client-python/blob/main/hubble/utils/auth.py#L39

But in notebook, they can't do that?

**Comment by bwanglzu** [comment]
Why can't? Call login browser will show up and then you just login😅

**Comment by mapleeit** [comment]
https://colab.research.google.com/drive/17Nr30xt_oLSTVCaPXV6v-9x74nHPZ01F?usp=sharing

It will get stucked here. Am I doing any thing wrong? If so, could you add your snippet here so I can try it out.

**Comment by bwanglzu** [comment]
wired, it worked in notebook, not working in google colab, let me see

**Comment by mapleeit** [comment]
Ok. I see. Maybe jupyter notebook is more powerful. Then let's get this merged. 

We can solve the bug in jupyter first. Then we'll fix the one in google colab.

**Review by mapleeit — APPROVED** [review]

**Comment by bwanglzu** [comment]
wait

**Comment by mapleeit** [comment]
@nomagick seems an easier way?

**Comment by bwanglzu** [comment]
i just tested, still not working on colab.. only work in notebook

**Comment by bwanglzu** [comment]
note: only jupyter notebook is working, google colab is not working.

**Review by jupyterjazz — APPROVED** [review]

**Pull request merged**
